services:
  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    ports:
        - ${DB_PORT}:3306
    volumes:
        - ./db/data:/var/lib/mysql
        - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: db
      PMA_USER: root
      PMA_PASSWORD: ${ROOT_PASS}
    ports:
      - "3000:80"
    volumes:
      - ./phpmyadmin/sessions:/sessions